// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Universidad.Models;

public partial class Curso
{
    [Key]
    [StringLength(8)]
    [Unicode(false)]
    public string Sigla { get; set; }

    [Required]
    [StringLength(40)]
    [Unicode(false)]
    public string Nombre { get; set; }

    public byte Creditos { get; set; }

    [InverseProperty("SiglaCursoNavigation")]
    public virtual ICollection<Grupo> Grupo { get; set; } = new List<Grupo>();
}