// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Universidad.Models;

public partial class Escuela
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string Codigo { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string CodFacultad { get; set; }

    [InverseProperty("CodEscuelaNavigation")]
    public virtual ICollection<Carrera> Carrera { get; set; } = new List<Carrera>();

    [ForeignKey("CodFacultad")]
    [InverseProperty("Escuela")]
    public virtual Facultad CodFacultadNavigation { get; set; }
}