// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Universidad.Models;

[PrimaryKey("SiglaCurso", "NumGrupo", "Semestre", "Anno")]
public partial class Grupo
{
    [Key]
    [StringLength(8)]
    [Unicode(false)]
    public string SiglaCurso { get; set; }

    [Key]
    public byte NumGrupo { get; set; }

    [Key]
    public byte Semestre { get; set; }

    [Key]
    public int Anno { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string CedProf { get; set; }

    public byte Carga { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string CedAsist { get; set; }

    [ForeignKey("CedAsist")]
    [InverseProperty("Grupo")]
    public virtual Asistente CedAsistNavigation { get; set; }

    [ForeignKey("CedProf")]
    [InverseProperty("Grupo")]
    public virtual Profesor CedProfNavigation { get; set; }

    [ForeignKey("SiglaCurso")]
    [InverseProperty("Grupo")]
    public virtual Curso SiglaCursoNavigation { get; set; }
}