// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Universidad.Models;

public partial class Asistente
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string Cedula { get; set; }

    public byte? NumHoras { get; set; }

    [ForeignKey("Cedula")]
    [InverseProperty("Asistente")]
    public virtual Estudiante CedulaNavigation { get; set; }

    [InverseProperty("CedAsistNavigation")]
    public virtual ICollection<Grupo> Grupo { get; set; } = new List<Grupo>();
}