// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Universidad.Models;

[PrimaryKey("CedEstudiante", "CodCarrera")]
public partial class Empadronado_en
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string CedEstudiante { get; set; }

    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string CodCarrera { get; set; }

    [Column(TypeName = "date")]
    public DateTime? FechaIngreso { get; set; }

    [Column(TypeName = "date")]
    public DateTime? FechaGraduacion { get; set; }

    [ForeignKey("CedEstudiante")]
    [InverseProperty("Empadronado_en")]
    public virtual Estudiante CedEstudianteNavigation { get; set; }

    [ForeignKey("CodCarrera")]
    [InverseProperty("Empadronado_en")]
    public virtual Carrera CodCarreraNavigation { get; set; }
}