// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Universidad.Models;

public partial class Investigacion
{
    [Key]
    [StringLength(15)]
    [Unicode(false)]
    public string NumProy { get; set; }

    [Required]
    [StringLength(80)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Area { get; set; }

    [Column(TypeName = "date")]
    public DateTime FechaInicio { get; set; }

    [Column(TypeName = "date")]
    public DateTime FechaFin { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    [InverseProperty("NumProyNavigation")]
    public virtual ICollection<Participa_en> Participa_en { get; set; } = new List<Participa_en>();
}