// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Universidad.Models;

[PrimaryKey("CedProf", "NumProy")]
public partial class Participa_en
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string CedProf { get; set; }

    [Key]
    [StringLength(15)]
    [Unicode(false)]
    public string NumProy { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Puesto { get; set; }

    public byte Carga { get; set; }

    [ForeignKey("CedProf")]
    [InverseProperty("Participa_en")]
    public virtual Profesor CedProfNavigation { get; set; }

    [ForeignKey("NumProy")]
    [InverseProperty("Participa_en")]
    public virtual Investigacion NumProyNavigation { get; set; }
}