// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Universidad.Models;

[PrimaryKey("SiglaCursoRequeridor", "SiglaCursoRequisito")]
public partial class Requiere_De
{
    [Key]
    [StringLength(8)]
    [Unicode(false)]
    public string SiglaCursoRequeridor { get; set; }

    [Key]
    [StringLength(8)]
    [Unicode(false)]
    public string SiglaCursoRequisito { get; set; }

    [ForeignKey("SiglaCursoRequeridor")]
    [InverseProperty("Requiere_DeSiglaCursoRequeridorNavigation")]
    public virtual Curso SiglaCursoRequeridorNavigation { get; set; }

    [ForeignKey("SiglaCursoRequisito")]
    [InverseProperty("Requiere_DeSiglaCursoRequisitoNavigation")]
    public virtual Curso SiglaCursoRequisitoNavigation { get; set; }
}