// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Universidad.Models;

[PrimaryKey("CedProf", "CodEscuela")]
public partial class Trabaja_en
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string CedProf { get; set; }

    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string CodEscuela { get; set; }

    [ForeignKey("CedProf")]
    [InverseProperty("Trabaja_en")]
    public virtual Profesor CedProfNavigation { get; set; }

    [ForeignKey("CodEscuela")]
    [InverseProperty("Trabaja_en")]
    public virtual Escuela CodEscuelaNavigation { get; set; }
}